name: Read Markdown Last Line

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  read-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read last line of markdown file
        run: |
          if [ -f README.md ]; then
            last_line=$(tail -n 1 README.md)
            echo "Last line of README.md: $last_line"
          else
            echo "README.md not found"
            exit 1
          fi