name: Read Markdown Last Line

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  read-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the PR branch and base for diff

      - name: Get changed markdown files and read last line
        run: |
          # Get list of changed .md files in the PR
          changed_files=$(git diff --name-only HEAD^ HEAD | grep '\.md$')
          
          if [ -z "$changed_files" ]; then
            echo "No .md files changed in this PR"
            exit 0
          fi
          
          # Loop through each changed .md file
          for file in $changed_files; do
            if [ -f "$file" ]; then
              last_line=$(tail -n 1 "$file")
              echo "Last line of $file: $last_line"
            else
              echo "File $file not found"
            fi
          done