name: Read Markdown Image Lines

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  read-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the PR branch and base for diff

      - name: Get changed markdown files and find image lines
        run: |
          # Get list of changed .md files in the PR
          changed_files=$(git diff --name-only HEAD^ HEAD | grep '\.md$')
          
          if [ -z "$changed_files" ]; then
            echo "No .md files changed in this PR"
            exit 0
          fi
          
          # Loop through each changed .md file
          for file in $changed_files; do
            if [ -f "$file" ]; then
              echo "Checking $file for image lines:"
              # Find lines matching Markdown image syntax ![alt](image-path)
              grep -E '!\[.*\]\(.*\)' "$file" | while IFS= read -r line; do
                echo "Found image line: $line"
              done
            else
              echo "File $file not found"
            fi
          done