name: Read Markdown Image Lines

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  read-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the PR branch and base for diff

      - name: Get changed markdown files and validate image lines
        run: |
          # Get list of changed .md files in the PR
          changed_files=$(git diff --name-only HEAD^ HEAD | grep '\.md$')
          
          if [ -z "$changed_files" ]; then
            echo "No .md files changed in this PR"
            exit 0
          fi
          
          # Initialize flag for invalid images
          has_invalid_images=false
          
          # Loop through each changed .md file
          for file in $changed_files; do
            if [ -f "$file" ]; then
              echo "Checking $file for image lines:"
              # Find lines matching Markdown image syntax ![alt](image-path)
              grep -n -E '!\[.*\]\(.*\)' "$file" | while IFS= read -r line; do
                echo "Found image line: $line"
                
                # Extract the image path from the Markdown image syntax
                image_path=$(echo "$line" | sed -E 's/.*!\[.*\]\((.*)\).*/\1/')
                
                # Check if image path is empty
                if [ -z "$image_path" ]; then
                  echo "Warning: Empty image path in line: $line"
                  has_invalid_images=true
                  continue
                fi
                
                # Check if image path has a valid extension (png, jpg, jpeg, gif, svg)
                if ! echo "$image_path" | grep -qE '\.(png|jpg|jpeg|gif|svg)$'; then
                  echo "Warning: Invalid or missing image extension in line: $line"
                  has_invalid_images=true
                fi
              done
            else
              echo "File $file not found"
            fi
          done
          
          # Exit with error code if invalid images were found
          if [ "$has_invalid_images" = true ]; then
            echo "Validation failed: Found invalid image formats in Markdown files"
            exit 1
          else
            echo "All image formats are valid"
          fi