name: Hugo Image Validation
on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'content/**.md'
      - 'content/**.markdown'
      - 'static/images/**'
permissions:
  pull-requests: write
  issues: write

jobs:
  validate-images:
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Comment starting point
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.pull_request.number }}
          id: image-validation
          message: "Starting [Hugo Image Validation](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})..."
          recreate: true
          append: false
